pipeline {
  agent { kubernetes 'kubernetes' } 

  tools{
    maven 'maven 3.6.1'  
  }
  stages{
    stage("build"){
      when{
        changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'env; mvn compile'
        }
      }
    }
    stage("test"){
      when{
        changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    stage("package"){
      when{
        changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn package -DskipTests'
          sh 'ls -lah; ls -lah target'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
  }
  post{
    always{
      echo 'Building pipeline for worker is completed..'}
    }
  }
